Sprint 3: Increment 13
a-bondar/go-url-shortener pull request #14
Opened 2024-06-19 14:08 UTC by a-bondar

2024-06-21 21:06 UTC, s-shpak requested changes

2024-06-21 21:06 UTC, s-shpak commented on cmd/shortener/main.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
Лишний импорт

2024-06-21 21:06 UTC, s-shpak commented on internal/app/store/db_store.go
> +	db, err := sql.Open("pgx", dsn)
Я настоятельно рекомендую не использовать `database/sql`, а вместо него использовать `pgx` напрямую. Это очень упростит работу + использование pgx напрямую - де-факто стандарт в индустрии. При этом стоит, конечно, исползовать не голое соединение, а `pgxpool`

2024-06-21 21:06 UTC, s-shpak commented on internal/app/store/db_store.go
> +		id SERIAL PRIMARY KEY,
1. Поменяй на миграции (можно в 4-м спринте)
2. Не используй SERIAL - этот подход устарел. Посмотри как я делаю здесь: https://github.com/s-shpak/yabinar-3.1-postgres/blob/8f38b3202addc21d04caa1c547864570a7038b3f/app/internal/datagen/datagen.go#L66

2024-06-21 21:06 UTC, s-shpak commented on internal/app/store/db_store.go
> +		short_url TEXT NOT NULL UNIQUE,
`TEXT` использовать не очень хорошо, см. здесь почему и что использовать вместо: https://www.brandur.org/text

2024-06-21 21:06 UTC, s-shpak commented on internal/app/store/db_store.go
> +		txErr := tx.Rollback()
Лучше вызывать роллбэк в defer - так ты даешь большую гарантию, что не забудешь его вызвать в случае ошибки

2024-06-23 16:12 UTC, a-bondar commented
Добавил миграции - упали тесты (спросил в пачке) https://app.pachca.com/chats/9384000?message=265961800

2024-06-24 17:33 UTC, s-shpak requested changes

2024-06-24 17:33 UTC, s-shpak commented on internal/app/store/db_store.go
> +		if errors.As(err, &pgErr) && pgerrcode.IsIntegrityConstraintViolation(pgErr.Code) {
`Integrity constraint violation` может возникнуть в двух случаях: 1. если `shortURL` не уникальна 2. если `fullURL` не уникальна. Эти два случая, как ты помнишь, обрабатываются по-разному. Как в данном случае удостовериться, что коллизи произошла не из-за `shortURL`, а из-за `fullURL` ?

2024-06-24 17:33 UTC, s-shpak commented on internal/app/store/db_store.go
> +			err = s.pool.QueryRow(ctx, selectQuery, fullURL).Scan(&existingShortURL)
Это второй запрос внутри одной операции, надо обернуть в транзакцию

2024-06-24 17:33 UTC, s-shpak commented on internal/app/store/db_store.go
> +	"log"
Не используй пакет `log`, используй свой кастомный логгер

2024-06-24 17:33 UTC, s-shpak commented on internal/app/store/db_store.go
> +	_, err = tx.Prepare(ctx, "insertSmt", "INSERT INTO short_links (original_url, short_url) VALUES ($1, $2)")
Это дорого: используй лучше https://pkg.go.dev/github.com/jackc/pgx/v5#Batch

2024-06-25 19:55 UTC, a-bondar commented on internal/app/store/db_store.go
> +			err = s.pool.QueryRow(ctx, selectQuery, fullURL).Scan(&existingShortURL)
не понял как, уточнил в пачке https://app.pachca.com/chats/9384000?message=267388634

2024-06-27 19:33 UTC, a-bondar commented on internal/app/store/db_store.go
> +			err = s.pool.QueryRow(ctx, selectQuery, fullURL).Scan(&existingShortURL)
поправил!

2024-06-27 22:55 UTC, s-shpak approved these changes

2024-06-28 09:50 UTC, merged