Sprint 4: Increment 15
a-bondar/go-url-shortener pull request #16
Opened 2024-07-08 12:30 UTC by a-bondar

2024-07-08 15:08 UTC, a-bondar commented on internal/app/handlers/handlers.go
> +	if err := h.s.DeleteURLs(r.Context(), request, userID); err != nil {
не понял как тут прикрутить горутины, тем более что тесты проходят и в БД использую батч

2024-07-09 09:41 UTC, s-shpak requested changes

2024-07-09 09:41 UTC, s-shpak commented on db/migrations/00003_add_deleted_to_short_links.up.sql
> +    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
У тебя неправильно теперь работает мягкое удаление: если ссылка помечена на удаление, ни дупликат короткой ссылки, ни дупликат полной все равно нельзя вставить в таблицу.

2024-07-09 09:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	userID, err := middleware.GetUserID(cookie.Value)
Почему бы не использовать здесь `GetUserIDFromContext` ?

2024-07-09 09:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	buf := new(bytes.Buffer)
```suggestion
	var buf bytes.Buffer
```

2024-07-09 09:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	if err := h.s.DeleteURLs(r.Context(), request, userID); err != nil {
Не надо, задание так себе составлено. Но добавь дополнительно компонент, который будет периодически удалять помеченные к удалению ссылки

2024-07-09 09:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(w, "", http.StatusBadRequest)
1. Если это `Bad request`, то ошибку не нужно логировать, т.к. она штатная
2. Это не `Bad request`

2024-07-09 09:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	userID, _ := middleware.GetUserIDFromContext(r.Context())
Второй аргумент надо проверять

2024-07-09 09:41 UTC, s-shpak commented on internal/app/middleware/auth.go
> +func GetUserIDFromContext(ctx context.Context) (string, bool) {
Лучше возвращать ошибку в таких случаях: ее можно использовать как `bool` (`if err != nil`), при этом в нее можно поместить дополнительный контекст

2024-07-09 09:41 UTC, s-shpak commented on internal/app/store/migrations/00002_add_user_id_to_short_links.down.sql
Почему у тебя в проекте миграции дублированы ?

2024-07-09 09:41 UTC, s-shpak commented on internal/app/store/in_memory_store.go
> +func (s *inMemoryStore) SaveURL(_ context.Context, fullURL string, shortURL string, userID string) (string, error) {
Обрати внимание, что попытка вставить уже существующие в таблице `fullURL` или `shortURL` не должна приводить к коллизии, если соответствующие записи помечены как удаленные

2024-07-10 07:46 UTC, a-bondar commented on internal/app/store/migrations/00002_add_user_id_to_short_links.down.sql
Забыл удалить после того как в папку store/migrations перенес, поправлю

2024-07-10 12:20 UTC, s-shpak requested changes

2024-07-10 12:20 UTC, s-shpak commented on internal/app/store/db_store.go
> +			ON CONFLICT (original_url) DO
А что если конфилкутет `short_url`, когда она мягко удалена ?

2024-07-11 10:20 UTC, a-bondar commented on internal/app/store/db_store.go
> +			ON CONFLICT (original_url) DO
По идее тут надо добавить еще одно условие в CTE, правда в таком случае оно будет уж очень большое + надо будет 2 `INSERT` делать. Других вариантов я пока не вижу

2024-07-11 10:33 UTC, a-bondar commented on internal/app/store/db_store.go
> +			ON CONFLICT (original_url) DO
а нет, так не сработает

2024-07-11 10:41 UTC, a-bondar commented on internal/app/store/db_store.go
> +			ON CONFLICT (original_url) DO
уточнил в пачке https://app.pachca.com/chats/9384000?message=280236188

2024-07-11 14:19 UTC, a-bondar commented on internal/app/store/db_store.go
> +			ON CONFLICT (original_url) DO
добавил partial_index на short_url

2024-07-12 13:31 UTC, s-shpak approved these changes

2024-08-13 09:24 UTC, merged