Sprint 1: Increment 5
a-bondar/go-url-shortener pull request #5
Opened 2024-05-06 10:31 UTC by a-bondar

2024-05-10 14:17 UTC, s-shpak requested changes
Настрой `golangci-lint` для запуска при помощи Github Actions, см. здесь как https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions. Поправь проблемы, которые линтер обнаружит

Поправь `metricstest` и `statictest` как описано здесь: https://app.pachca.com/chats/9180496?message=230119157

Обрати внимание, что я пометил не все проблемные места в коде: если одна и та же ошибка встречается несколько раз, то надо поправить ее везде

2024-05-10 14:17 UTC, s-shpak commented on go.mod
> +go 1.21.9
```suggestion
go 1.22.2
```

2024-05-10 14:17 UTC, s-shpak commented on internal/app/config/config.go
> +	if envRunAddr := os.Getenv("SERVER_ADDRESS"); envRunAddr != "" {
Лучше используй `https://pkg.go.dev/os#LookupEnv`

2024-05-10 14:17 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +var linksMap = map[string]string{}
Глобальные переменные не нужны

2024-05-10 14:17 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Внутренние ошибки надо логировать

2024-05-10 14:17 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	sEnc := base64.StdEncoding.EncodeToString(body)
Это не сокращение ссылок. почитай в интернете, как можно задизайнить такой сервис

2024-05-10 14:17 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	if _, err := w.Write([]byte(cfg.ShortLinkBaseURL + "/" + sEnc)); err != nil {
Лучше используй https://pkg.go.dev/net/url#JoinPath

2024-05-15 23:44 UTC, s-shpak requested changes
Не резолвь, пожалуйста, комменты - оставляй это мне, чтобы мне было легче понять, что я просил изменить

2024-05-15 23:44 UTC, s-shpak commented on internal/app/utils/utils.go
Пакет `utils` - анти-паттерн, здесь обсуждение почему: https://www.reddit.com/r/Python/comments/rh006y/why_the_hate_for_utils_modules_what_is_the/

Помести этот функционал в тот пакет, где он используется

2024-05-15 23:44 UTC, s-shpak commented on internal/app/utils/utils.go
> +	chars := []rune("ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
Я бы вынес это на уровень пакета, чтобы точно не создавать это каждый раз при вызове функции

2024-05-15 23:44 UTC, s-shpak commented on internal/app/service/service.go
> +		} else {
Этот else не нужен

2024-05-15 23:44 UTC, s-shpak commented on cmd/shortener/main.go
> +	fmt.Println("Running server on:", cfg.RunAddr)
```suggestion
	log.Printf("Running server on: %s", cfg.RunAddr)
```

2024-05-16 16:04 UTC, a-bondar commented on internal/app/utils/utils.go
я его вынес отдельно чтобы в тестах передать внутрь сервиса мок-функцию генерации случайной строки (которая будет возвращать одно и то же), в противном случае непонятно как протестировать корректную работу сокращения ссылки т.к. каждый раз генерируется случайная строка

2024-05-16 19:06 UTC, a-bondar commented on internal/app/utils/utils.go
в итоге замокал service в тестах

2024-05-21 08:09 UTC, s-shpak approved these changes

2024-05-23 09:20 UTC, merged